version: '3.1'

services:
  mongo:
    image: mongo:8.0.1
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example      
    networks:
      - rede

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: macacodump
      ME_CONFIG_MONGODB_ADMINPASSWORD: macaco
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - rede
    depends_on:
      - mongo
  
networks:
  rede:
    driver: bridge